### PR TITLE
Add KMS signer

### PR DESCRIPTION
**Pull request by wchenNL**
TODO
- add tests
- update readme

### CODE REVIEW

**Comment by alisinabh** [comment]
Hey @wchenNL,

This is amazing and I love it. Let's have a chat in the week to discuss how we should include it since this adds quite a lot of dependencies to the package.

Thank you very much for the amazing work 💜

**Comment by wchenNL** [comment]
> Hey @wchenNL,
> 
> This is amazing and I love it. Let's have a chat in the week to discuss how we should include it since this adds quite a lot of dependencies to the package.
> 
> Thank you very much for the amazing work 💜

👍 Understood, for majority this signer may not be interesting to them. Hence adding those dependencies is not the best.
I think I may be able to implement the signer behaviour in a separate service.

**Comment by tzumby** [comment]
> > Hey @wchenNL,
> > This is amazing and I love it. Let's have a chat in the week to discuss how we should include it since this adds quite a lot of dependencies to the package.
> > Thank you very much for the amazing work 💜
> 
> 👍 Understood, for majority this signer may not be interesting to them. Hence adding those dependencies is not the best. I think I may be able to implement the signer behaviour in a separate service.

I think that's what I would recommend as well. `libcluster` has a nice model with Strategies that are separate repos:
ie: https://github.com/bitwalker/libcluster
and strategies:
- https://github.com/kyleaa/libcluster_ec2
- https://github.com/supabase/libcluster_postgres
etc

I think this would keep elixir_ethers nice and clean :)

**Comment by wchenNL** [comment]
closing this now because it has been worked on in a separate lib https://github.com/ExWeb3/elixir_ethers_kms/pull/1

**Pull request closed without merging**
